package: massif_settings
version: '1.1.0'
author: Yves Torres (ynamite)
supportpage: https://massif.ch/

requires:
  redaxo: '^5.0'
  php: '>=7.4'
  massif: '^1.0.0'

page:
  title: Stammdaten
  perm: massif_settings[]
  icon: rex-icon fa-gears
