package: massif_settings
version: '1.0.0'
author: Yves Torres (ynamite)
supportpage: https://massif.ch/

requires:
  redaxo: '^5.0'
  php: '>=7.4'
  massif: '^1.0.0'

page:
  title: Stammdaten
  perm: massif_settings[]
  icon: rex-icon fa-gears
  subpages:
    address:
      title: 'Stammdaten'
      icon: 'fa fa-map-pin'
      fields:
        [
          { name: 'firma', label: 'Name', notice: '{{address_firma}}' },
          {
            name: 'firma_zusatz',
            label: 'Zusatz',
            notice: '{{address_firma_zusatz}}'
          },
          { name: 'strasse', label: 'Strasse', notice: '{{address_strasse}}' },
          { name: 'plz', label: 'PLZ', notice: '{{address_plz}}' },
          { name: 'ort', label: 'Ort', notice: '{{address_ort}}' },
          {
            name: 'kanton_code',
            label: 'Kanton-Code',
            notice: '{{address_kanton_code}}'
          },
          { name: 'land', label: 'Land', notice: '{{address_land}}' },
          {
            name: 'land_code',
            label: 'Land-Code',
            notice: '{{address_land_code}}'
          },
          {
            name: 'e-mail',
            label: 'E-Mail',
            formatter: 'email',
            notice: '{{address_email}}'
          },
          {
            name: 'phone',
            label: 'Telefon',
            formatter: 'phone',
            notice: '{{address_phone}}'
          }
        ]
    google:
      title: 'Google'
      icon: 'fa fa-location-dot'
      fields:
        [
          {
            name: 'maps_link',
            label: 'Google Maps Link',
            notice: '{{google_maps_link}}'
          },
          {
            name: 'geo lat.',
            label: 'Geo Lat.',
            style_input: 'font-weight:bold',
            notice: '{{google_geo_lat}}'
          },
          {
            name: 'geo long.',
            label: 'Geo Long.',
            style_input: 'font-weight:bold',
            notice: '{{google_geo_long}}'
          }
        ]
    social:
      title: 'Social Media'
      icon: 'fa fa-linkedin'
      fields:
        [
          {
            name: 'instagram',
            label: 'Instagram',
            notice: '{{social_instagram}}',
            formatter: 'url'
          },
          {
            name: 'linkedin',
            label: 'LinkedIn',
            notice: '{{social_linkedin}}',
            formatter: 'url'
          }
        ]
    settings:
      title: 'Einstellungen'
      icon: 'fa fa-cog'
      fields:
        [
          {
            name: 'accent_color',
            label: 'Akzentfarbe',
            class: 'minicolors-massif',
            default: '#ff269e'
          }
        ]
